services:
  api:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Api__Keys__0=dev-secret-key-change-me
      - JobQueue__SeedDefaults=true
      - LLM__ModelPath=/models/qwen3-1_5-instruct-q4_0.gguf
      - LLM__ContextTokens=4096
      - LLM__Threads=6
      - LLM__MaxTokens=512
      - LLM__Temperature=0.2
      - LLM__ThinkingMode=auto
    ports: [ "5214:8080" ]
    volumes:
      - ../models:/models:ro
